openapi: 3.0.0
info:
  version: '2.0'
  title: Square ApplePay Customers API
  description: 'Supercharge Square for sellers of every size. Our entire connected commerce platform  from elegant hardware to a rich suite of Square APIs  is yours to build with. Whether youre developing an app or composing a bespoke solution, this is the place to make it happen. '
  termsOfService: https://connect.squareup.com/tos
  contact:
    name: Square Developer Platform
    email: developers@squareup.com
    url: https://squareup.com/developers
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-server-configuration:
    default-environment: production
    default-server: default
    environments:
    - name: production
      servers:
      - name: default
        url: https://connect.squareup.com
    - name: sandbox
      servers:
      - name: default
        url: https://connect.squareupsandbox.com
    - name: custom
      servers:
      - name: default
        url: '{custom_url}'
  x-square-generic-error-codes:
  - ACCESS_TOKEN_EXPIRED
  - ACCESS_TOKEN_REVOKED
  - API_VERSION_INCOMPATIBLE
  - APPLICATION_DISABLED
  - ARRAY_EMPTY
  - ARRAY_LENGTH_TOO_LONG
  - ARRAY_LENGTH_TOO_SHORT
  - BAD_CERTIFICATE
  - BAD_GATEWAY
  - BAD_REQUEST
  - CONFLICT
  - CONFLICTING_PARAMETERS
  - CURRENCY_MISMATCH
  - EXPECTED_ARRAY
  - EXPECTED_BASE64_ENCODED_BYTE_ARRAY
  - EXPECTED_BOOLEAN
  - EXPECTED_FLOAT
  - EXPECTED_INTEGER
  - EXPECTED_JSON_BODY
  - EXPECTED_MAP
  - EXPECTED_OBJECT
  - EXPECTED_STRING
  - FORBIDDEN
  - GATEWAY_TIMEOUT
  - GONE
  - IDEMPOTENCY_KEY_REUSED
  - INCORRECT_TYPE
  - INSUFFICIENT_SCOPES
  - INTERNAL_SERVER_ERROR
  - INVALID_ARRAY_VALUE
  - INVALID_CONTENT_TYPE
  - INVALID_CURSOR
  - INVALID_ENUM_VALUE
  - INVALID_FORM_VALUE
  - INVALID_SORT_ORDER
  - INVALID_SQUARE_VERSION_FORMAT
  - INVALID_TIME
  - INVALID_TIME_RANGE
  - INVALID_VALUE
  - LOCATION_MISMATCH
  - MAP_KEY_LENGTH_TOO_LONG
  - MAP_KEY_LENGTH_TOO_SHORT
  - MERCHANT_SUBSCRIPTION_NOT_FOUND
  - METHOD_NOT_ALLOWED
  - MISSING_REQUIRED_PARAMETER
  - NOT_ACCEPTABLE
  - NOT_FOUND
  - NOT_IMPLEMENTED
  - NO_FIELDS_SET
  - RATE_LIMITED
  - REQUEST_ENTITY_TOO_LARGE
  - REQUEST_TIMEOUT
  - SANDBOX_NOT_SUPPORTED
  - SERVICE_UNAVAILABLE
  - TOO_MANY_MAP_ENTRIES
  - UNAUTHORIZED
  - UNEXPECTED_VALUE
  - UNKNOWN_BODY_PARAMETER
  - UNKNOWN_QUERY_PARAMETER
  - UNPROCESSABLE_ENTITY
  - UNSUPPORTED_MEDIA_TYPE
  - V1_ACCESS_TOKEN
  - V1_APPLICATION
  - VALUE_EMPTY
  - VALUE_REGEX_MISMATCH
  - VALUE_TOO_HIGH
  - VALUE_TOO_LONG
  - VALUE_TOO_LOW
  - VALUE_TOO_SHORT
servers:
- url: https://connect.squareup.com
  variables: {}
tags:
- name: Customers
paths:
  /v2/customers:
    get:
      tags:
      - Customers
      summary: Square List Customers
      operationId: ListCustomers
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Lists customer profiles associated with a Square account.


        Under normal operating conditions, newly created or updated customer profiles become available

        for the listing operation in well under 30 seconds. Occasionally, propagation of the new or updated

        profiles can take closer to one minute or longer, especially during network incidents and outages.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_READ
    post:
      tags:
      - Customers
      summary: Square Create Customer
      operationId: CreateCustomer
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Creates a new customer for a business.


        You must provide at least one of the following values in your request to this

        endpoint:


        - `given_name`

        - `family_name`

        - `company_name`

        - `email_address`

        - `phone_number`'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-endpoint-errors:
      - error-code: INVALID_EMAIL_ADDRESS
      - error-code: INVALID_PHONE_NUMBER
      - error-code: INVALID_TIME
      - error-code: VALUE_TOO_LONG
  /v2/customers/bulk-create:
    post:
      tags:
      - Customers
      summary: Square Bulk Create Customers
      operationId: BulkCreateCustomers
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Creates multiple [customer profiles](entity:Customer) for a business.


        This endpoint takes a map of individual create requests and returns a map of responses.


        You must provide at least one of the following values in each create request:


        - `given_name`

        - `family_name`

        - `company_name`

        - `email_address`

        - `phone_number`'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_WRITE
  /v2/customers/bulk-delete:
    post:
      tags:
      - Customers
      summary: Square Bulk Delete Customers
      operationId: BulkDeleteCustomers
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Deletes multiple customer profiles.


        The endpoint takes a list of customer IDs and returns a map of responses.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_WRITE
  /v2/customers/bulk-retrieve:
    post:
      tags:
      - Customers
      summary: Square Bulk Retrieve Customers
      operationId: BulkRetrieveCustomers
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Retrieves multiple customer profiles.


        This endpoint takes a list of customer IDs and returns a map of responses.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_READ
  /v2/customers/bulk-update:
    post:
      tags:
      - Customers
      summary: Square Bulk Update Customers
      operationId: BulkUpdateCustomers
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Updates multiple customer profiles.


        This endpoint takes a map of individual update requests and returns a map of responses.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_WRITE
  /v2/customers/search:
    post:
      tags:
      - Customers
      summary: Square Search Customers
      operationId: SearchCustomers
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Searches the customer profiles associated with a Square account using one or more supported query filters.


        Calling `SearchCustomers` without any explicit query filter returns all

        customer profiles ordered alphabetically based on `given_name` and

        `family_name`.


        Under normal operating conditions, newly created or updated customer profiles become available

        for the search operation in well under 30 seconds. Occasionally, propagation of the new or updated

        profiles can take closer to one minute or longer, especially during network incidents and outages.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_READ
  /v2/customers/{customer_id}:
    delete:
      tags:
      - Customers
      summary: Square Delete Customer
      operationId: DeleteCustomer
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Deletes a customer profile from a business.


        To delete a customer profile that was created by merging existing profiles, you must use the ID of the newly created profile.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_WRITE
    get:
      tags:
      - Customers
      summary: Square Retrieve Customer
      operationId: RetrieveCustomer
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: Returns details for a single customer.
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_READ
    put:
      tags:
      - Customers
      summary: Square Update Customer
      operationId: UpdateCustomer
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Updates a customer profile. This endpoint supports sparse updates, so only new or changed fields are required in the request.

        To add or update a field, specify the new value. To remove a field, specify `null`.


        To update a customer profile that was created by merging existing profiles, you must use the ID of the newly created profile.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-endpoint-errors:
      - error-code: INVALID_EMAIL_ADDRESS
      - error-code: INVALID_PHONE_NUMBER
      - error-code: INVALID_TIME
      - error-code: VALUE_TOO_LONG
  /v2/customers/{customer_id}/cards:
    post:
      tags:
      - Customers
      summary: Square Create Customer Card
      operationId: CreateCustomerCard
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Adds a card on file to an existing customer.


        As with charges, calls to `CreateCustomerCard` are idempotent. Multiple

        calls with the same card nonce return the same card record that was created

        with the provided nonce during the _first_ call.'
      x-release-status: DEPRECATED
      deprecated: true
      x-deprecation:
        deprecationDate: '2021-06-16'
        replacedBy: CreateCard
        guideUrl: https://developer.squareup.com/docs/customers-api/what-it-does#deprecated-createcustomercard-endpoint
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-endpoint-errors:
      - error-code: CARD_EXPIRED
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CARD_TOKEN_EXPIRED
      - error-code: CARD_TOKEN_USED
      - error-code: INVALID_CARD
      - error-code: INVALID_CARD_DATA
      - error-code: INVALID_EXPIRATION
      - error-code: UNSUPPORTED_ENTRY_METHOD
      - error-code: VERIFY_AVS_FAILURE
      - error-code: VERIFY_CVV_FAILURE
  /v2/customers/{customer_id}/cards/{card_id}:
    delete:
      tags:
      - Customers
      summary: Square Delete Customer Card
      operationId: DeleteCustomerCard
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: Removes a card on file from a customer.
      x-release-status: DEPRECATED
      deprecated: true
      x-deprecation:
        deprecationDate: '2021-06-16'
        replacedBy: DisableCard
        guideUrl: https://developer.squareup.com/docs/customers-api/what-it-does#deprecated-deletecustomercard-endpoint
      security:
      - oauth2:
        - CUSTOMERS_WRITE
  /v2/customers/{customer_id}/groups/{group_id}:
    delete:
      tags:
      - Customers
      summary: Square Remove Group from Customer
      operationId: RemoveGroupFromCustomer
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Removes a group membership from a customer.


        The customer is identified by the `customer_id` value

        and the customer group is identified by the `group_id` value.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_WRITE
    put:
      tags:
      - Customers
      summary: Square Add Group to Customer
      operationId: AddGroupToCustomer
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Adds a group membership to a customer.


        The customer is identified by the `customer_id` value

        and the customer group is identified by the `group_id` value.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - CUSTOMERS_WRITE
components:
  securitySchemes:
    oauth2:
      type: oauth2
      x-additional-headers:
      - name: Square-Version
        description: Square Connect API versions
        schema:
          default: '2025-01-23'
      flows:
        authorizationCode:
          authorizationUrl: https://connect.squareup.com/oauth2/authorize
          tokenUrl: https://connect.squareup.com/oauth2/token
          scopes:
            ADDON_CONFIGURATIONS_READ: '__HTTP Method__: `GET`


              Grants write access for third-party Add-ons to read configurations of their Add-ons, for example, when calling `RetrieveConfiguration` endpoint.'
            ADDON_CONFIGURATIONS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access for third-party Add-ons to store configurations of their Add-ons, for example, when calling `CreateConfiguration` endpoint.'
            APPOINTMENTS_ALL_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to all of a seller''s booking information, calendar, and business details.

              This permission must be accompanied by the `APPOINTMENTS_READ` permission.'
            APPOINTMENTS_ALL_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to all booking details, including double-booking a seller.

              This permission must be accompanied by the `APPOINTMENTS_WRITE` permission.'
            APPOINTMENTS_BUSINESS_SETTINGS_READ: '__HTTP Method__: `GET`


              Grants read access to booking business settings. For example, to call the

              ListTeamMemberBookingProfiles endpoint.'
            APPOINTMENTS_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to booking information. For example, to call the

              RetrieveBooking endpoint.'
            APPOINTMENTS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to booking information. For example, to call the CreateBooking endpoint.'
            BANK_ACCOUNTS_READ: '__HTTP Method__: `GET`


              Grants read access to bank account information associated with the targeted

              Square account. For example, to call the Connect v1 ListBankAccounts endpoint.'
            CASH_DRAWER_READ: '__HTTP Method__: `GET`


              Grants read access to cash drawer shift information. For example, to call the

              ListCashDrawerShifts endpoint.'
            CHANNELS_CREATE: '__HTTP Method__: `POST`


              Grants write access to create channels, for example, when calling the

              `CreateChannel` endpoint.'
            CHANNELS_READ: '__HTTP Method__: `GET`


              Grants read access to view channels, for example, when calling the

              `RetrieveChannel` endpoint.'
            CHANNELS_UPDATE: '__HTTP Method__: `PUT`


              Grants write access to update channels, for example, when calling the

              `UpdateChannel` endpoint.'
            CUSTOMERS_READ: '__HTTP Method__: `GET`


              Grants read access to customer information. For example, to call the

              ListCustomers endpoint.'
            CUSTOMERS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to customer information. For example, to create and update

              customer profiles.'
            DEVICES_READ: '__HTTP Method__: `GET`


              Grants read access to device information. For example, to

              call the `GetDevice` and `ListDevices` endpoints.'
            DEVICE_CREDENTIAL_MANAGEMENT: '__HTTP Method__: `POST`, `GET`


              Grants read/write access to device credentials information. For example, to

              call the CreateDeviceCode endpoint.'
            DISPUTES_READ: '__HTTP Method__: `GET`


              Grants read access to dispute information. For example, to call the RetrieveDispute

              endpoint.'
            DISPUTES_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to dispute information. For example, to call the SubmitEvidence

              endpoint.'
            EMPLOYEES_READ: '__HTTP Method__: `GET`


              Grants read access to employee profile information. For example, to call the

              Connect v1 Employees API.'
            EMPLOYEES_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to employee profile information. For example, to create

              and modify employee profiles.'
            GIFTCARDS_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to gift card information. For example, to call the RetrieveGiftCard

              endpoint.'
            GIFTCARDS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to gift card information. For example, to call the CreateGiftCard

              endpoint.'
            INVENTORY_READ: '__HTTP Method__: `GET`


              Grants read access to inventory information. For example, to call the

              RetrieveInventoryCount endpoint.'
            INVENTORY_WRITE: '__HTTP Method__:  `POST`, `PUT`, `DELETE`


              Grants write access to inventory information. For example, to call the

              BatchChangeInventory endpoint.'
            INVOICES_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to invoice information. For example, to call the ListInvoices endpoint.'
            INVOICES_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to invoice information. For example, to call the CreateInvoice endpoint.'
            ITEMS_READ: '__HTTP Method__: `GET`


              Grants read access to product catalog information. For example, to obtain objects in a product catalog.'
            ITEMS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to product catalog information. For example, to modify or

              add to a product catalog.'
            LOYALTY_READ: '__HTTP Method__: `GET`


              Grants read access to loyalty information. For example, to call the

              ListLoyaltyPrograms endpoint.'
            LOYALTY_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to loyalty information. For example, to call the

              CreateLoyaltyAccount endpoint.'
            MERCHANT_PROFILE_READ: '__HTTP Method__: `GET`


              Grants read access to business and location information. For example, to

              obtain a location ID for subsequent activity.'
            MERCHANT_PROFILE_WRITE: '__HTTP Method__: `POST`, `PUT`


              Grants write access to business and location information. For example, to create a new location or

              update the business hours at an existing location.'
            ONLINE_STORE_SITE_READ: '__HTTP Method__: `GET`, `POST`


              Read access to ECOM online store site details.'
            ONLINE_STORE_SNIPPETS_READ: '__HTTP Method__: `GET`, `POST`


              Read access to ECOM online store snippets on published websites.'
            ONLINE_STORE_SNIPPETS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Write access to ECOM online store snippets on published websites.'
            ORDERS_READ: '__HTTP Method__: `GET`


              Grants read access to order information. For example, to call the

              BatchRetrieveOrders endpoint.'
            ORDERS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to order information. For example, to call the

              CreateCheckout endpoint.'
            PAYMENTS_READ: '__HTTP Method__: `GET`


              Grants read access to transaction and refund information. For example, to call

              the RetrieveTransaction endpoint.'
            PAYMENTS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to transaction and refunds information. For example, to

              process payments with the Payments or Checkout API.'
            PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Allow third party applications to deduct a portion of each transaction amount.

              __Required__ to use multiparty transaction functionality with the Payments

              API.'
            PAYMENTS_WRITE_IN_PERSON: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to payments and refunds information. For example, to

              process in-person payments.'
            PAYMENTS_WRITE_SHARED_ONFILE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Allows the developer to process payments on behalf of a seller using a shared on file payment method.'
            PAYOUTS_READ: '__HTTP Method__: `GET`


              Grants read access to payouts and payout entries information. For example,

              to call the Connect v2 `ListPayouts` endpoint.'
            PERMISSION_SETS_READ: '__HTTP Method__: `GET`


              Grants read access to Permission Sets. For example, to

              call the `ListPermissionSets` and `RetrievePermissionSet` endpoints.'
            PERMISSION_SETS_WRITE: '__HTTP Method__: `PUT`


              Grants write access to Permission Sets.'
            RESERVATIONS_READ: '__HTTP Method__: `GET`


              Grants read access to reservation information, for example, when calling the

              `RetrieveReservation` endpoint.'
            RESERVATIONS_WRITE: '__HTTP Method__:  `POST`, `PUT`, `DELETE`


              Grants write access to reservation information, for example, when calling the

              `CreateReservation` endpoint.'
            RESTAURANT_CHECKS_READ: '__HTTP Method__: `GET`


              Grants read access to check information, for example, when calling the

              `RetrieveCheck` endpoint.'
            SETTLEMENTS_READ: '__HTTP Method__: `GET`


              Grants read access to settlement (deposit) information. For example, to call

              the Connect v1 ListSettlements endpoint.'
            SUBSCRIPTIONS_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to subscription information. For example, to call the RetrieveSubscription

              endpoint.'
            SUBSCRIPTIONS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to subscription information. For example, to call the CreateSubscription

              endpoint.'
            TIMECARDS_READ: '__HTTP Method__: `GET`


              Grants read access to employee timecard information. For example, to call the

              Connect v2 SearchShifts endpoint.'
            TIMECARDS_SETTINGS_READ: '__HTTP Method__: `GET`


              Grants read access to employee timecard settings information. For example, to

              call the GetBreakType endpoint.'
            TIMECARDS_SETTINGS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to employee timecard settings information. For example, to

              call the UpdateBreakType endpoint.'
            TIMECARDS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to employee shift information. For example, to create

              and modify employee shifts.'
            VENDOR_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to vendor information, for example, when calling the

              `RetrieveVendor` endpoint.'
            VENDOR_WRITE: '__HTTP Method__:  `POST`, `PUT`, `DELETE`


              Grants write access to vendor information, for example, when calling the

              `BulkUpdateVendors` endpoint.'
    oauth2ClientSecret:
      type: apiKey
      in: header
      name: Authorization