openapi: 3.0.0
info:
  version: '2.0'
  title: Square ApplePay Catalog API
  description: 'Supercharge Square for sellers of every size. Our entire connected commerce platform  from elegant hardware to a rich suite of Square APIs  is yours to build with. Whether youre developing an app or composing a bespoke solution, this is the place to make it happen. '
  termsOfService: https://connect.squareup.com/tos
  contact:
    name: Square Developer Platform
    email: developers@squareup.com
    url: https://squareup.com/developers
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-server-configuration:
    default-environment: production
    default-server: default
    environments:
    - name: production
      servers:
      - name: default
        url: https://connect.squareup.com
    - name: sandbox
      servers:
      - name: default
        url: https://connect.squareupsandbox.com
    - name: custom
      servers:
      - name: default
        url: '{custom_url}'
  x-square-generic-error-codes:
  - ACCESS_TOKEN_EXPIRED
  - ACCESS_TOKEN_REVOKED
  - API_VERSION_INCOMPATIBLE
  - APPLICATION_DISABLED
  - ARRAY_EMPTY
  - ARRAY_LENGTH_TOO_LONG
  - ARRAY_LENGTH_TOO_SHORT
  - BAD_CERTIFICATE
  - BAD_GATEWAY
  - BAD_REQUEST
  - CONFLICT
  - CONFLICTING_PARAMETERS
  - CURRENCY_MISMATCH
  - EXPECTED_ARRAY
  - EXPECTED_BASE64_ENCODED_BYTE_ARRAY
  - EXPECTED_BOOLEAN
  - EXPECTED_FLOAT
  - EXPECTED_INTEGER
  - EXPECTED_JSON_BODY
  - EXPECTED_MAP
  - EXPECTED_OBJECT
  - EXPECTED_STRING
  - FORBIDDEN
  - GATEWAY_TIMEOUT
  - GONE
  - IDEMPOTENCY_KEY_REUSED
  - INCORRECT_TYPE
  - INSUFFICIENT_SCOPES
  - INTERNAL_SERVER_ERROR
  - INVALID_ARRAY_VALUE
  - INVALID_CONTENT_TYPE
  - INVALID_CURSOR
  - INVALID_ENUM_VALUE
  - INVALID_FORM_VALUE
  - INVALID_SORT_ORDER
  - INVALID_SQUARE_VERSION_FORMAT
  - INVALID_TIME
  - INVALID_TIME_RANGE
  - INVALID_VALUE
  - LOCATION_MISMATCH
  - MAP_KEY_LENGTH_TOO_LONG
  - MAP_KEY_LENGTH_TOO_SHORT
  - MERCHANT_SUBSCRIPTION_NOT_FOUND
  - METHOD_NOT_ALLOWED
  - MISSING_REQUIRED_PARAMETER
  - NOT_ACCEPTABLE
  - NOT_FOUND
  - NOT_IMPLEMENTED
  - NO_FIELDS_SET
  - RATE_LIMITED
  - REQUEST_ENTITY_TOO_LARGE
  - REQUEST_TIMEOUT
  - SANDBOX_NOT_SUPPORTED
  - SERVICE_UNAVAILABLE
  - TOO_MANY_MAP_ENTRIES
  - UNAUTHORIZED
  - UNEXPECTED_VALUE
  - UNKNOWN_BODY_PARAMETER
  - UNKNOWN_QUERY_PARAMETER
  - UNPROCESSABLE_ENTITY
  - UNSUPPORTED_MEDIA_TYPE
  - V1_ACCESS_TOKEN
  - V1_APPLICATION
  - VALUE_EMPTY
  - VALUE_REGEX_MISMATCH
  - VALUE_TOO_HIGH
  - VALUE_TOO_LONG
  - VALUE_TOO_LOW
  - VALUE_TOO_SHORT
servers:
- url: https://connect.squareup.com
  variables: {}
tags:
- name: Catalog
paths:
  /v2/catalog/batch-delete:
    post:
      tags:
      - Catalog
      summary: Square Batch Delete Catalog Objects
      operationId: BatchDeleteCatalogObjects
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Deletes a set of [CatalogItem](entity:CatalogItem)s based on the

        provided list of target IDs and returns a set of successfully deleted IDs in

        the response. Deletion is a cascading event such that all children of the

        targeted object are also deleted. For example, deleting a CatalogItem will

        also delete all of its [CatalogItemVariation](entity:CatalogItemVariation)

        children.


        `BatchDeleteCatalogObjects` succeeds even if only a portion of the targeted

        IDs can be deleted. The response will only include IDs that were

        actually deleted.


        To ensure consistency, only one delete request is processed at a time per seller account.

        While one (batch or non-batch) delete request is being processed, other (batched and non-batched)

        delete requests are rejected with the `429` error code.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_WRITE
  /v2/catalog/batch-retrieve:
    post:
      tags:
      - Catalog
      summary: Square Batch Retrieve Catalog Objects
      operationId: BatchRetrieveCatalogObjects
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Returns a set of objects based on the provided ID.

        Each [CatalogItem](entity:CatalogItem) returned in the set includes all of its

        child information including: all of its

        [CatalogItemVariation](entity:CatalogItemVariation) objects, references to

        its [CatalogModifierList](entity:CatalogModifierList) objects, and the ids of

        any [CatalogTax](entity:CatalogTax) objects that apply to it.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_READ
  /v2/catalog/batch-upsert:
    post:
      tags:
      - Catalog
      summary: Square Batch Upsert Catalog Objects
      operationId: BatchUpsertCatalogObjects
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Creates or updates up to 10,000 target objects based on the provided

        list of objects. The target objects are grouped into batches and each batch is

        inserted/updated in an all-or-nothing manner. If an object within a batch is

        malformed in some way, or violates a database constraint, the entire batch

        containing that item will be disregarded. However, other batches in the same

        request may still succeed. Each batch may contain up to 1,000 objects, and

        batches will be processed in order as long as the total object count for the

        request (items, variations, modifier lists, discounts, and taxes) is no more

        than 10,000.


        To ensure consistency, only one update request is processed at a time per seller account.

        While one (batch or non-batch) update request is being processed, other (batched and non-batched)

        update requests are rejected with the `429` error code.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_WRITE
      x-endpoint-errors:
      - error-code: GENERIC_DECLINE
  /v2/catalog/images:
    post:
      tags:
      - Catalog
      summary: Square Create Catalog Image
      operationId: CreateCatalogImage
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Uploads an image file to be represented by a [CatalogImage](entity:CatalogImage) object that can be linked to an existing

        [CatalogObject](entity:CatalogObject) instance. The resulting `CatalogImage` is unattached to any `CatalogObject` if the `object_id`

        is not specified.


        This `CreateCatalogImage` endpoint accepts HTTP multipart/form-data requests with a JSON part and an image file part in

        JPEG, PJPEG, PNG, or GIF format. The maximum file size is 15MB.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_WRITE
      x-endpoint-errors:
      - error-code: GENERIC_DECLINE
  /v2/catalog/images/{image_id}:
    put:
      tags:
      - Catalog
      summary: Square Update Catalog Image
      operationId: UpdateCatalogImage
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Uploads a new image file to replace the existing one in the specified [CatalogImage](entity:CatalogImage) object.


        This `UpdateCatalogImage` endpoint accepts HTTP multipart/form-data requests with a JSON part and an image file part in

        JPEG, PJPEG, PNG, or GIF format. The maximum file size is 15MB.'
      x-release-status: BETA
      security:
      - oauth2:
        - ITEMS_WRITE
  /v2/catalog/info:
    get:
      tags:
      - Catalog
      summary: Square Catalog Info
      operationId: CatalogInfo
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Retrieves information about the Square Catalog API, such as batch size

        limits that can be used by the `BatchUpsertCatalogObjects` endpoint.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_READ
  /v2/catalog/list:
    get:
      tags:
      - Catalog
      summary: Square List Catalog
      operationId: ListCatalog
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Returns a list of all [CatalogObject](entity:CatalogObject)s of the specified types in the catalog.


        The `types` parameter is specified as a comma-separated list of the [CatalogObjectType](entity:CatalogObjectType) values,

        for example, "`ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, `CATEGORY`, `DISCOUNT`, `TAX`, `IMAGE`".


        __Important:__ ListCatalog does not return deleted catalog items. To retrieve

        deleted catalog items, use [SearchCatalogObjects](api-endpoint:Catalog-SearchCatalogObjects)

        and set the `include_deleted_objects` attribute value to `true`.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_READ
  /v2/catalog/object:
    post:
      tags:
      - Catalog
      summary: Square Upsert Catalog Object
      operationId: UpsertCatalogObject
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Creates a new or updates the specified [CatalogObject](entity:CatalogObject).


        To ensure consistency, only one update request is processed at a time per seller account.

        While one (batch or non-batch) update request is being processed, other (batched and non-batched)

        update requests are rejected with the `429` error code.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_WRITE
      x-endpoint-errors:
      - error-code: GENERIC_DECLINE
      - error-code: INVALID_LOCATION
  /v2/catalog/object/{object_id}:
    delete:
      tags:
      - Catalog
      summary: Square Delete Catalog Object
      operationId: DeleteCatalogObject
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Deletes a single [CatalogObject](entity:CatalogObject) based on the

        provided ID and returns the set of successfully deleted IDs in the response.

        Deletion is a cascading event such that all children of the targeted object

        are also deleted. For example, deleting a [CatalogItem](entity:CatalogItem)

        will also delete all of its

        [CatalogItemVariation](entity:CatalogItemVariation) children.


        To ensure consistency, only one delete request is processed at a time per seller account.

        While one (batch or non-batch) delete request is being processed, other (batched and non-batched)

        delete requests are rejected with the `429` error code.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_WRITE
    get:
      tags:
      - Catalog
      summary: Square Retrieve Catalog Object
      operationId: RetrieveCatalogObject
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Returns a single [CatalogItem](entity:CatalogItem) as a

        [CatalogObject](entity:CatalogObject) based on the provided ID. The returned

        object includes all of the relevant [CatalogItem](entity:CatalogItem)

        information including: [CatalogItemVariation](entity:CatalogItemVariation)

        children, references to its

        [CatalogModifierList](entity:CatalogModifierList) objects, and the ids of

        any [CatalogTax](entity:CatalogTax) objects that apply to it.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_READ
  /v2/catalog/search:
    post:
      tags:
      - Catalog
      summary: Square Search Catalog Objects
      operationId: SearchCatalogObjects
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Searches for [CatalogObject](entity:CatalogObject) of any type by matching supported search attribute values,

        excluding custom attribute values on items or item variations, against one or more of the specified query filters.


        This (`SearchCatalogObjects`) endpoint differs from the [SearchCatalogItems](api-endpoint:Catalog-SearchCatalogItems)

        endpoint in the following aspects:


        - `SearchCatalogItems` can only search for items or item variations, whereas `SearchCatalogObjects` can search for any type of catalog objects.

        - `SearchCatalogItems` supports the custom attribute query filters to return items or item variations that contain custom attribute values, where `SearchCatalogObjects` does not.

        - `SearchCatalogItems` does not support the `include_deleted_objects` filter to search for deleted items or item variations, whereas `SearchCatalogObjects` does.

        - The both endpoints have different call conventions, including the query filter formats.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_READ
  /v2/catalog/search-catalog-items:
    post:
      tags:
      - Catalog
      summary: Square Search Catalog Items
      operationId: SearchCatalogItems
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Searches for catalog items or item variations by matching supported search attribute values, including

        custom attribute values, against one or more of the specified query filters.


        This (`SearchCatalogItems`) endpoint differs from the [SearchCatalogObjects](api-endpoint:Catalog-SearchCatalogObjects)

        endpoint in the following aspects:


        - `SearchCatalogItems` can only search for items or item variations, whereas `SearchCatalogObjects` can search for any type of catalog objects.

        - `SearchCatalogItems` supports the custom attribute query filters to return items or item variations that contain custom attribute values, where `SearchCatalogObjects` does not.

        - `SearchCatalogItems` does not support the `include_deleted_objects` filter to search for deleted items or item variations, whereas `SearchCatalogObjects` does.

        - The both endpoints use different call conventions, including the query filter formats.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_READ
  /v2/catalog/update-item-modifier-lists:
    post:
      tags:
      - Catalog
      summary: Square Update Item Modifier Lists
      operationId: UpdateItemModifierLists
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Updates the [CatalogModifierList](entity:CatalogModifierList) objects

        that apply to the targeted [CatalogItem](entity:CatalogItem) without having

        to perform an upsert on the entire item.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_WRITE
  /v2/catalog/update-item-taxes:
    post:
      tags:
      - Catalog
      summary: Square Update Item Taxes
      operationId: UpdateItemTaxes
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      description: 'Updates the [CatalogTax](entity:CatalogTax) objects that apply to the

        targeted [CatalogItem](entity:CatalogItem) without having to perform an

        upsert on the entire item.'
      x-release-status: PUBLIC
      security:
      - oauth2:
        - ITEMS_WRITE
components:
  securitySchemes:
    oauth2:
      type: oauth2
      x-additional-headers:
      - name: Square-Version
        description: Square Connect API versions
        schema:
          default: '2025-01-23'
      flows:
        authorizationCode:
          authorizationUrl: https://connect.squareup.com/oauth2/authorize
          tokenUrl: https://connect.squareup.com/oauth2/token
          scopes:
            ADDON_CONFIGURATIONS_READ: '__HTTP Method__: `GET`


              Grants write access for third-party Add-ons to read configurations of their Add-ons, for example, when calling `RetrieveConfiguration` endpoint.'
            ADDON_CONFIGURATIONS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access for third-party Add-ons to store configurations of their Add-ons, for example, when calling `CreateConfiguration` endpoint.'
            APPOINTMENTS_ALL_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to all of a seller''s booking information, calendar, and business details.

              This permission must be accompanied by the `APPOINTMENTS_READ` permission.'
            APPOINTMENTS_ALL_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to all booking details, including double-booking a seller.

              This permission must be accompanied by the `APPOINTMENTS_WRITE` permission.'
            APPOINTMENTS_BUSINESS_SETTINGS_READ: '__HTTP Method__: `GET`


              Grants read access to booking business settings. For example, to call the

              ListTeamMemberBookingProfiles endpoint.'
            APPOINTMENTS_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to booking information. For example, to call the

              RetrieveBooking endpoint.'
            APPOINTMENTS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to booking information. For example, to call the CreateBooking endpoint.'
            BANK_ACCOUNTS_READ: '__HTTP Method__: `GET`


              Grants read access to bank account information associated with the targeted

              Square account. For example, to call the Connect v1 ListBankAccounts endpoint.'
            CASH_DRAWER_READ: '__HTTP Method__: `GET`


              Grants read access to cash drawer shift information. For example, to call the

              ListCashDrawerShifts endpoint.'
            CHANNELS_CREATE: '__HTTP Method__: `POST`


              Grants write access to create channels, for example, when calling the

              `CreateChannel` endpoint.'
            CHANNELS_READ: '__HTTP Method__: `GET`


              Grants read access to view channels, for example, when calling the

              `RetrieveChannel` endpoint.'
            CHANNELS_UPDATE: '__HTTP Method__: `PUT`


              Grants write access to update channels, for example, when calling the

              `UpdateChannel` endpoint.'
            CUSTOMERS_READ: '__HTTP Method__: `GET`


              Grants read access to customer information. For example, to call the

              ListCustomers endpoint.'
            CUSTOMERS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to customer information. For example, to create and update

              customer profiles.'
            DEVICES_READ: '__HTTP Method__: `GET`


              Grants read access to device information. For example, to

              call the `GetDevice` and `ListDevices` endpoints.'
            DEVICE_CREDENTIAL_MANAGEMENT: '__HTTP Method__: `POST`, `GET`


              Grants read/write access to device credentials information. For example, to

              call the CreateDeviceCode endpoint.'
            DISPUTES_READ: '__HTTP Method__: `GET`


              Grants read access to dispute information. For example, to call the RetrieveDispute

              endpoint.'
            DISPUTES_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to dispute information. For example, to call the SubmitEvidence

              endpoint.'
            EMPLOYEES_READ: '__HTTP Method__: `GET`


              Grants read access to employee profile information. For example, to call the

              Connect v1 Employees API.'
            EMPLOYEES_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to employee profile information. For example, to create

              and modify employee profiles.'
            GIFTCARDS_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to gift card information. For example, to call the RetrieveGiftCard

              endpoint.'
            GIFTCARDS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to gift card information. For example, to call the CreateGiftCard

              endpoint.'
            INVENTORY_READ: '__HTTP Method__: `GET`


              Grants read access to inventory information. For example, to call the

              RetrieveInventoryCount endpoint.'
            INVENTORY_WRITE: '__HTTP Method__:  `POST`, `PUT`, `DELETE`


              Grants write access to inventory information. For example, to call the

              BatchChangeInventory endpoint.'
            INVOICES_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to invoice information. For example, to call the ListInvoices endpoint.'
            INVOICES_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to invoice information. For example, to call the CreateInvoice endpoint.'
            ITEMS_READ: '__HTTP Method__: `GET`


              Grants read access to product catalog information. For example, to obtain objects in a product catalog.'
            ITEMS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to product catalog information. For example, to modify or

              add to a product catalog.'
            LOYALTY_READ: '__HTTP Method__: `GET`


              Grants read access to loyalty information. For example, to call the

              ListLoyaltyPrograms endpoint.'
            LOYALTY_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to loyalty information. For example, to call the

              CreateLoyaltyAccount endpoint.'
            MERCHANT_PROFILE_READ: '__HTTP Method__: `GET`


              Grants read access to business and location information. For example, to

              obtain a location ID for subsequent activity.'
            MERCHANT_PROFILE_WRITE: '__HTTP Method__: `POST`, `PUT`


              Grants write access to business and location information. For example, to create a new location or

              update the business hours at an existing location.'
            ONLINE_STORE_SITE_READ: '__HTTP Method__: `GET`, `POST`


              Read access to ECOM online store site details.'
            ONLINE_STORE_SNIPPETS_READ: '__HTTP Method__: `GET`, `POST`


              Read access to ECOM online store snippets on published websites.'
            ONLINE_STORE_SNIPPETS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Write access to ECOM online store snippets on published websites.'
            ORDERS_READ: '__HTTP Method__: `GET`


              Grants read access to order information. For example, to call the

              BatchRetrieveOrders endpoint.'
            ORDERS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to order information. For example, to call the

              CreateCheckout endpoint.'
            PAYMENTS_READ: '__HTTP Method__: `GET`


              Grants read access to transaction and refund information. For example, to call

              the RetrieveTransaction endpoint.'
            PAYMENTS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to transaction and refunds information. For example, to

              process payments with the Payments or Checkout API.'
            PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Allow third party applications to deduct a portion of each transaction amount.

              __Required__ to use multiparty transaction functionality with the Payments

              API.'
            PAYMENTS_WRITE_IN_PERSON: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to payments and refunds information. For example, to

              process in-person payments.'
            PAYMENTS_WRITE_SHARED_ONFILE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Allows the developer to process payments on behalf of a seller using a shared on file payment method.'
            PAYOUTS_READ: '__HTTP Method__: `GET`


              Grants read access to payouts and payout entries information. For example,

              to call the Connect v2 `ListPayouts` endpoint.'
            PERMISSION_SETS_READ: '__HTTP Method__: `GET`


              Grants read access to Permission Sets. For example, to

              call the `ListPermissionSets` and `RetrievePermissionSet` endpoints.'
            PERMISSION_SETS_WRITE: '__HTTP Method__: `PUT`


              Grants write access to Permission Sets.'
            RESERVATIONS_READ: '__HTTP Method__: `GET`


              Grants read access to reservation information, for example, when calling the

              `RetrieveReservation` endpoint.'
            RESERVATIONS_WRITE: '__HTTP Method__:  `POST`, `PUT`, `DELETE`


              Grants write access to reservation information, for example, when calling the

              `CreateReservation` endpoint.'
            RESTAURANT_CHECKS_READ: '__HTTP Method__: `GET`


              Grants read access to check information, for example, when calling the

              `RetrieveCheck` endpoint.'
            SETTLEMENTS_READ: '__HTTP Method__: `GET`


              Grants read access to settlement (deposit) information. For example, to call

              the Connect v1 ListSettlements endpoint.'
            SUBSCRIPTIONS_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to subscription information. For example, to call the RetrieveSubscription

              endpoint.'
            SUBSCRIPTIONS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to subscription information. For example, to call the CreateSubscription

              endpoint.'
            TIMECARDS_READ: '__HTTP Method__: `GET`


              Grants read access to employee timecard information. For example, to call the

              Connect v2 SearchShifts endpoint.'
            TIMECARDS_SETTINGS_READ: '__HTTP Method__: `GET`


              Grants read access to employee timecard settings information. For example, to

              call the GetBreakType endpoint.'
            TIMECARDS_SETTINGS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to employee timecard settings information. For example, to

              call the UpdateBreakType endpoint.'
            TIMECARDS_WRITE: '__HTTP Method__: `POST`, `PUT`, `DELETE`


              Grants write access to employee shift information. For example, to create

              and modify employee shifts.'
            VENDOR_READ: '__HTTP Method__: `GET`, `POST`


              Grants read access to vendor information, for example, when calling the

              `RetrieveVendor` endpoint.'
            VENDOR_WRITE: '__HTTP Method__:  `POST`, `PUT`, `DELETE`


              Grants write access to vendor information, for example, when calling the

              `BulkUpdateVendors` endpoint.'
    oauth2ClientSecret:
      type: apiKey
      in: header
      name: Authorization